<?
	 function getPosts(){
		 $posts = array('PRESIDENT','VICE_PRESIDENT','GENERAL_SECRETARY','FINANCIAL_SECRETARY','PRO','SOCIAL_DIRECTOR','SPORTS_DIRECTOR','AGS','FASSA_REPRESENTATIVE1','FASSA_REPRESENTATIVE2','ASST_SOCIAL_DIRECTOR');
		 
		 return $posts;
	 }
?>